### ISSUE TITLE
Phoenix.HTML.Safe not implemented for #AshPhoenix.Form

### ISSUE THREAD

**Issue by carlgleisner** [ash-project/ash_admin#121]
**Describe the bug**

Navigating to the `update` action of a resource with a `belongs_to` relationship to another resource crashes with the error `protocol Phoenix.HTML.Safe not implemented for #AshPhoenix.Form[…]`.

Please note that this works just fine in my Phoenix app ⚠️

**To Reproduce**

The resource that `belongs_to` another resource. It is redacted and reduced to what is pertinent because that is what I provide at the moment.

```elixir
defmodule MyApp.MyDomain.MyResource do
  use Ash.Resource,
    domain: MyApp.MyDomain,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAdmin.Resource, AshStateMachine]

  postgres do
    table "my_domain_my_resources"
    repo MyApp.Repo
  end

  attributes do
    uuid_primary_key :id

    create_timestamp :created_at
    create_timestamp :updated_at
  end

  relationships do
    belongs_to :my_related_resource, MyApp.MyDomain.MyRelatedResource do
      allow_nil? false
    end
  end

  actions do
    defaults [:read, :destroy]
    default_accept :*

    create :create do
      primary? true

      argument :my_related_resource_id, :uuid do
        allow_nil? false
      end

      argument :court_id, :uuid do
        allow_nil? false
      end

      argument :claims_harvester_id, :uuid

      change manage_relationship(:my_related_resource_id, :my_related_resource, type: :append_and_remove)

      change relate_actor(:created_by)
    end

    update :update do
      argument :my_related_resource_id, :uuid do
        allow_nil? false
      end

      require_atomic? false

      change manage_relationship(:my_related_resource_id, :my_related_resource, type: :append_and_remove)
    end
  end


  admin do
    form do
      field :some_comment, type: :long_text
    end
  end
end
```
The related resource that the previous one belongs to.

```elixir
defmodule MyApp.MyDomain.MyRelatedResource do
  use Ash.Resource,
    domain: MyApp.MyDomain,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAdmin.Resource, AshArchival.Resource]

  postgres do
    table "my_domain_my_realted_resources"
    repo MyApp.Repo
  end

  attributes do
    uuid_primary_key :id

    create_timestamp :created_at
    create_timestamp :updated_at
  end

  actions do
    defaults [:create, :read, :update]
    default_accept :*

    destroy :destroy do
      require_atomic? false
    end
  end
end
```

The error output.

```
[error] GenServer #PID<0.9786.0> terminating
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for #AshPhoenix.Form<resource: MyApp.MyDomain.MyRelatedResource, action: :read, type: :read, params: %{"id" => "c24b2a79-a013-4111-8191-b841c7c4f991"}, source: #Ash.Query<resource: MyApp.MyDomain.MyRelatedResource, filter: #Ash.Filter<archived_at is nil>>, name: "form[my_resource_id]", data: #MyApp.MyDomain.MyRelatedResource<__meta__: #Ecto.Schema.Metadata<:loaded, "my_domain_my_resource">, archived_at: nil, id: "c24b2a79-a013-4111-8191-b841c7c4f991", name: "name", something_id: "[redacted]", something_else_id: "[redacted]", created_at: ~U[2024-03-06 02:40:16.910858Z], updated_at: ~U[2024-03-06 02:40:16.910858Z], aggregates: %{}, calculations: %{}, ...>, form_keys: [], forms: %{}, domain: MyApp.MyDomain, method: "post", submit_errors: nil, id: "form_my_resource_id", transform_errors: #Function<3.101091702/2 in AshAdmin.Components.Resource.Form.assign_form/1>, original_data: nil, transform_params: #Function<39.62187671/3 in AshPhoenix.Form.Auto.related/3>, prepare_params: nil, prepare_source: nil, warn_on_unhandled_errors?: true, any_removed?: false, added?: false, changed?: false, touched_forms: MapSet.new(["id"]), valid?: true, errors: false, submitted_once?: false, just_submitted?: false, ...> of type AshPhoenix.Form (a struct). This protocol is implemented for the following type(s): Ash.CiString, Ash.NotLoaded, Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, Money, NaiveDateTime, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
    (phoenix_html 4.1.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
    (phoenix_html 4.1.1) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
    (phoenix_html 4.1.1) lib/phoenix_html.ex:238: Phoenix.HTML.build_attrs/1
    (phoenix_html 4.1.1) lib/phoenix_html.ex:191: Phoenix.HTML.attributes_escape/1
    (ash_admin 0.10.10-rc.1) lib/ash_admin/components/core_components.ex:366: anonymous fn/2 in AshAdmin.CoreComponents."input (overridable 1)"/1
    (ash_admin 0.10.10-rc.1) /Users/username/Developer/my_app/deps/ash_admin/lib/ash_admin/components/resource/form.ex:776: AshAdmin.Components.Resource.Form.render_attribute_input/6
    (elixir 1.16.1) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.16.1) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:573: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/5
    (elixir 1.16.1) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.1) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.1) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.1) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:494: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.59>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.2781554790.1804337155.144331>, start_time: -576460661694657815, start_metadata: %{telemetry_span_context: #Reference<0.2781554790.1804337155.144331>, remote_port: 60242, remote_address: {127, 0, 0, 1}, parent_telemetry_span_context: #Reference<0.2781554790.1804337155.142621>}}}, %{opts: %{http: [], websocket: [], http_1: [], http_2: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {MyAppWeb.Endpoint, []}}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true}}
```

**Expected behavior**

The admin liveview should render properly, that is not crash but rather show a field for the relationship to the related resource.

**Runtime**
 - Elixir `1.16.1-otp-26`
 - Erlang `26.1.2`
 - macOS Sonoma 14.4.1 `Darwin Kernel Version 23.4.0`
 - `ash 3.0.0-rc.27`, `ash_admin 0.10.10-rc.1`, `ash_phoenix 2.0.0-rc.6`

**Additional context**

Please note that this works just fine in my Phoenix app ⚠️

**Comment by zachdaniel** [comment]
So, we wouldn't implement that protocol for the form, this is likely indicating some other issue. The question is now to isolate it to something unique about the specific relationship you're having issues with. Unless you're seeing this for *all* belongs_to relationships?

**Comment by sevenseacat** [comment]
This is the same as I was telling you about the other day that I was fixing in our apps, when we did the argument/manage_relationship way of handling `belongs_to` relationships. And yes, we were seeing it for *all* of them.

You can get around the error by rewriting the action a little bit - instead of having an argument with the foreign key and using `manage_relationship`, you can set `attribute_writable? true` on the relationship and then treat the foreign key like any other attribute, eg.

```elixir
relationships do 
  belongs_to :my_related_resource, MyApp.MyDomain.MyRelatedResource do
    attribute_writable? true
    allow_nil? false
  end
end

actions do 
  create :create do 
    accept [:my_related_resource_id]
  end
end
```

**Comment by zachdaniel** [comment]
I will look into this soon, but I have a feeling this is something quite simple under the hood.

**Comment by zachdaniel** [comment]
Hopefully can get to it tonight/tomorrow.

**Comment by carlgleisner** [comment]
I've been trying to make time to try a new resource but I've been swamped with fires to put out. Thanks for getting back!

I feel that it's on my end somehow and I want to avoid wasting other people's time (generally do!).

Will have a look today Sunday.
