### ISSUE TITLE
LiveView crash when removing one element of a many-to-many relationship on a Create form

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_admin#14]
**Describe the bug**
On a Create form for a new resource that has a many-to-many relationship with another resource, Ash admin builds a section to add/remove new records of the relationship. eg. in our app we have a resource that has `many_to_many :competencies`:

<img width="440" alt="Screen Shot 2022-05-18 at 3 49 01 pm" src="https://user-images.githubusercontent.com/543859/168986230-86481548-b643-4883-8e98-22a467d16820.png">

When clicking the minus icon to remove one of the items in the list, the LiveView crashes:

```
** (Protocol.UndefinedError) protocol Phoenix.HTML.FormData not implemented for #Ash.Changeset<action_type: :create, action: :create, (lots of other stuff omitted)> of type Ash.Changeset (a struct). This protocol is implemented for the following type(s): AshPhoenix.FilterForm, AshPhoenix.FilterForm.Predicate, AshPhoenix.Form, Atom, Ecto.Changeset, Plug.Conn
    (phoenix_html 3.2.0) lib/phoenix_html/form_data.ex:1: Phoenix.HTML.FormData.impl_for!/1
    (phoenix_html 3.2.0) lib/phoenix_html/form_data.ex:34: Phoenix.HTML.FormData.input_value/3
    (ash_admin 0.4.4) lib/ash_admin/components/resource/form.ex:1119: AshAdmin.Components.Resource.Form.remove_value/3
    (ash_admin 0.4.4) lib/ash_admin/components/resource/form.ex:1036: AshAdmin.Components.Resource.Form.handle_event/3
```

**Expected behavior**
The element (form field and minus icon) should be removed from the page, without LiveView crashing.

** Runtime
 - Elixir version - 1.13.3
 - Erlang version - 24.3
 - OS - MacOS Monterey 12.3
 - Ash version - main branch (sha 78671725429d38562be477715925b72500cbcdaa0ebf80b3378e374a2e9a95d0)
 - Ash admin version - 0.4.4

**Comment by zachdaniel** [comment]
🤔 Yeah, that looks pretty suspect...can you try using the latest release candidate of liveview and see if that resolves the issue? I've pinned it to the latest release candidate of AshPhoenix which has had a lot of work done on those operations.

**Comment by Theosaurus-Rex** [comment]
@zachdaniel I've just tried this with the latest release and unfortunately still seeing the same issue. This is happening in a couple of places in our project - I've also had the issue with coordinate fields on another resource:
<img width="588" alt="Screen Shot 2022-05-19 at 8 59 49 am" src="https://user-images.githubusercontent.com/71990001/169168919-88549c6d-5ad0-4105-b5e6-58163c6a20e2.png">
