### ISSUE TITLE
Compilation error with Phoenix 1.7

### ISSUE THREAD

**Issue by minibikini** [ash-project/ash_admin#35]
**Describe the bug**

In Phoenix 1.7 project compilation fails with this error:

```
== Compilation error in file lib/my_app_web/router.ex ==
** (RuntimeError) attempting to redefine live_session :default.
live_session routes must be declared in a single named block.

    (phoenix_live_view 0.18.3) lib/phoenix_live_view/router.ex:237: Phoenix.LiveView.Router.__live_session__/3
    lib/my_app_web/router.ex:37: (module)
    (elixir 1.14.2) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

**To Reproduce**
Add `ash_admin` macro to the router file of Phoenix 1.7-rc0 application.

**Expected behavior**
No errors

**Runtime**
 - Elixir version 1.14.2
 - Erlang version 25
 - Ash version 2.4.24
 - AshAdmin 0.7.0
 - Phoenix 1.7-rc0
 - Phoenix LiveView 0.18.3

**Comment by minibikini** [comment]
Same error on [`phoenix-1.7` branch](https://github.com/ash-project/ash_admin/tree/phoenix-1.7) too.

**Comment by zachdaniel** [comment]
Thanks for the report! can you try out the phoenix-1.7 branch again?

**Comment by minibikini** [comment]
Error message is slightly different now (~~`redefine live_session :default`~~ `redefine live_session :ash_admin`):

```
== Compilation error in file lib/table_hero_web/router.ex ==
** (RuntimeError) attempting to redefine live_session :ash_admin.
live_session routes must be declared in a single named block.

    (phoenix_live_view 0.18.3) lib/phoenix_live_view/router.ex:237: Phoenix.LiveView.Router.__live_session__/3
```

**Comment by zachdaniel** [comment]
🤔 are you calling the function twice?

**Comment by minibikini** [comment]
oh yes, sorry

![image](https://i.pinimg.com/originals/ae/47/6d/ae476d8033bcf74d4a8dbad7741eaeaa.gif)

all good now, closing the issue.
