### ISSUE TITLE
Crash when a resource has no actions defined.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash_admin#47]
`ash_admin` assumes that a resource will have at least one read action. When it doesn't it crashes due to a match error:

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a nonempty list

    :erlang.hd([])
    (ash_admin 0.8.0) lib/ash_admin/components/top_nav/dropdown.ex:62: anonymous fn/4 in AshAdmin.Components.TopNav.Dropdown."render (overridable 1)"/1
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash_admin 0.8.0) lib/ash_admin/components/top_nav/dropdown.ex:60: anonymous fn/2 in AshAdmin.Components.TopNav.Dropdown."render (overridable 1)"/1
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/diff.ex:398: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/diff.ex:373: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/diff.ex:717: Phoenix.LiveView.Diff.render_component/9
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/diff.ex:210: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.18.16) lib/phoenix_live_view/channel.ex:544: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by zachdaniel** [comment]
Fixed in main
